name: Build, Test, Package and Push

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events and merges/pushes to main
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  schedule:
    # Daily 5am australian/brisbane time
    - cron: '19 0 * * *'
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # all

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Nuke Build 🏗
        id: build
        env:
          OCTOVERSION_CurrentBranch: ${{ github.head_ref || github.ref }} # For pull_request events we override the /refs/pull/xx/merge branch to the PR's head branch
          OCTOVERSION_Patch: ${{ github.run_number }}
        shell: bash
        run: ./build.sh --verbosity verbose

      - name: Install Octopus CLI 🐙
        uses: OctopusDeploy/install-octopus-cli-action@v1
        with:
          version: latest
        
      - name: Push to Octopus 🐙
        uses: OctopusDeploy/push-package-action@v1
        with:
          server: ${{ secrets.DEPLOY_URL }}
          space: Core Platform
          api_key: ${{ secrets.DEPLOY_API_KEY }}
          packages: |
            ./artifacts/Octopus.Server.Extensibility.${{ steps.build.outputs.octoversion_fullsemver }}.nupkg          

      - name: Create Release in Octopus 🐙
        uses: OctopusDeploy/create-release-action@v1
        with:
          server: ${{ secrets.DEPLOY_URL }}
          space: Core Platform
          api_key: ${{ secrets.DEPLOY_API_KEY }}
          project: "ServerExtensibility"
          packages: |
            Octopus.Server.Extensibility:${{ steps.build.outputs.octoversion_fullsemver }}
        
      - name: Tag release (when not pre-release) 🏷️
        if: ${{ !contains( steps.build.outputs.octoversion_fullsemver, '-' ) }}
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.build.outputs.octoversion_fullsemver }}",
              sha: context.sha
            })
